version: '3.4'
services:
  mssqlserver:
    container_name: online_shop_app_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1Secure*Password1
    
  onlineshopwebapp:
    container_name: online_shop_app_mvc
    image: stanislavchetverukhin/online_shop_web_app:latest
    ports:
      - 5001:80
    depends_on:
      - mssqlserver    
