// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Db;

namespace OnlineShop.Db.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InfoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InfoId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.OrderInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostIndex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OrderInfo");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Айзек Азимов",
                            Cost = 595.0m,
                            Genre = "Фантастика",
                            ImageLink = "https://ndc.book24.ru/resize/820x1192/iblock/f21/f21f9483ee3861d440665b4411f2279e/300a6c758a8bdfeda1f6f5afc27b563e.jpg",
                            Isbn = "978-5-04-100014-1",
                            Name = "Я, Робот",
                            Pages = 320,
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Author = "Айзек Азимов",
                            Cost = 434.0m,
                            Genre = "Фантастика",
                            ImageLink = "https://ndc.book24.ru/resize/820x1192/iblock/181/181beb5dbd902b55a4765e70e51231b8/aa10e3358076daa167348bc844c9decb.jpg",
                            Isbn = "978-5-04-093907-7",
                            Name = "Академия",
                            Pages = 320,
                            Year = 2022
                        },
                        new
                        {
                            Id = 3,
                            Author = "Джек Лондон",
                            Cost = 299.0m,
                            Genre = "Приключения",
                            ImageLink = "https://ndc.book24.ru/resize/820x1192/iblock/5b5/5b5af79c1d0c3a5847ad835b4c97d075/0ec5f7e31d749f17f26ebaa637afa619.jpg",
                            Isbn = "978-5-04-155023-3",
                            Name = "Сердца трех",
                            Pages = 384,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Author = "Маккарти Кормак",
                            Cost = 708.0m,
                            Genre = "Фантастика",
                            ImageLink = "https://ndc.book24.ru/resize/820x1192/iblock/be0/be0ddf53becceba6ff022c04d56b5817/d6b8855b357edfb326b31a88e8b96def.jpg",
                            Isbn = "978-5-389-14385-2",
                            Name = "Дорога",
                            Pages = 320,
                            Year = 2018
                        },
                        new
                        {
                            Id = 5,
                            Author = "Джон Стейнбек",
                            Cost = 575.0m,
                            Genre = "Проза",
                            ImageLink = "https://ndc.book24.ru/resize/820x1192/iblock/ea9/ea9eb4a164eac48fe14c20638213e01c/a47a1686f161bdce78d32b30e6975f3d.jpg",
                            Isbn = "978-5-17-982853-2",
                            Name = "О мышах и людях",
                            Pages = 256,
                            Year = 2020
                        },
                        new
                        {
                            Id = 6,
                            Author = "Терри Пратчетт",
                            Cost = 745.0m,
                            Genre = "Фэнтези",
                            ImageLink = "https://cdn.book24.ru/v2/ITD000000001286313/COVER/cover13d__w410.webp",
                            Isbn = "978-5-04-170567-1",
                            Name = "Пастушья корона",
                            Pages = 384,
                            Year = 2023
                        },
                        new
                        {
                            Id = 7,
                            Author = "Анджей Сапковский",
                            Cost = 519.0m,
                            Genre = "Фэнтези",
                            ImageLink = "https://cdn.book24.ru/v2/AST000000000025472/COVER/cover13d__w410.webp",
                            Isbn = "978-5-17-074112-0",
                            Name = "Меч Предназначения",
                            Pages = 384,
                            Year = 2022
                        },
                        new
                        {
                            Id = 8,
                            Author = "Стиг Ларссон",
                            Cost = 602.0m,
                            Genre = "Детектив",
                            ImageLink = "https://ndc.book24.ru/resize/820x1180/iblock/bad/bad1a2e028d38c5ff25cc194e3275574/5df4501d6356f6c94d8b22ca34519707.jpg",
                            Isbn = "978-5-04-102885-5",
                            Name = "Девушка с татуировкой дракона",
                            Pages = 576,
                            Year = 2022
                        },
                        new
                        {
                            Id = 9,
                            Author = "Дуглас Адамс",
                            Cost = 920.0m,
                            Genre = "Фантастика",
                            ImageLink = "https://ndc.book24.ru/resize/820x1192/iblock/ab1/ab139c2bdf94259370f5da9644a72663/487613949db6b3eb04c94490ce202e69.jpg",
                            Isbn = "978-5-17-098748-1",
                            Name = "Автостопом по галактике",
                            Pages = 640,
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            Author = "Джордж Р.Р. Мартин",
                            Cost = 819.0m,
                            Genre = "Фэнтези",
                            ImageLink = "https://ndc.book24.ru/resize/820x1180/iblock/d78/d782032aeb2a79f720423b339a16fb1a/cf9f7284d68e3dd7b9d1b7b8a7ff9c61.jpg",
                            Isbn = "978-5-17-077386-2",
                            Name = "Путешествия Тафа",
                            Pages = 480,
                            Year = 2019
                        },
                        new
                        {
                            Id = 11,
                            Author = "Томас Харрис",
                            Cost = 406.0m,
                            Genre = "Детектив",
                            ImageLink = "https://ndc.book24.ru/resize/820x1180/iblock/8ed/8edd954668cc5946b2d8be98162e19d9/b19b90e38142864977c6c73d0337437d.jpg",
                            Isbn = "978-5-04-170567-1",
                            Name = "Кари Мора",
                            Pages = 320,
                            Year = 2019
                        },
                        new
                        {
                            Id = 12,
                            Author = "Ю Несбё",
                            Cost = 406.0m,
                            Genre = "Детектив",
                            ImageLink = "https://ndc.book24.ru/resize/820x1180/iblock/155/1552f2966a722870dc095b98c65ce911/9e2a0c4e892877fc299aae3b78658668.jpg",
                            Isbn = "978-5-04-092924-5",
                            Name = "Макбет",
                            Pages = 608,
                            Year = 2019
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartProduct", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Cart", null)
                        .WithMany("CartProducts")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.Db.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.Db.Models.Product", "Product")
                        .WithMany("CartProducts")
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.OrderInfo", "Info")
                        .WithMany()
                        .HasForeignKey("InfoId");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Navigation("CartProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
